{{- if and (.Values.namespacedOperator) (not .Values.clusterOnly) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-operator-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-role
rules:
- apiGroups: ["", "cluster.ray.io"]
  resources: ["rayclusters", "rayclusters/finalizers", "rayclusters/status", "pods", "pods/exec", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: ray-operator-serviceaccount
roleRef:
  kind: Role
  name: ray-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.ray.io/component: operator
  template:
    metadata:
      labels:
        cluster.ray.io/component: operator
      annotations:
        {{ include "coeus.annotations" . | nindent 8}}
    spec:
      nodeSelector:
        {{- include "coeus.nodeSelector" . | indent 8}}
      hostAliases:
        {{ include "coeus.hostAliases" . | nindent 8}}
      imagePullSecrets:
        {{include "coeus.imagePullSecrets" . | nindent 8}}
      dnsPolicy: None
      {{ include "coeus.dnsConfig" . | nindent 6}}
      serviceAccountName: ray-operator-serviceaccount
      containers:
      - name: ray
        imagePullPolicy: Always
        image: {{ .Values.operatorImage }}
        command: ["ray-operator"]
        env:
        - name: RAY_OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AUTOSCALER_MAX_NUM_FAILURES
          value: "inf"
        {{include "coeus.envs" . | indent 8}}
        resources:
          requests:
            cpu: 4
            memory: 10Gi
            ephemeral-storage: 10Gi
          limits:
            memory: 20Gi
            cpu: 8
{{- end }}
